# splat configuration for Stretch Panic (USA) SLUS_201.82
name: stretch-panic-usa
sha1: 0a330e76424b7254e4096d8809b2a927603d3581
options:
  basename: SLUS_201.82
  target_path: orig/SLUS_201.82/SLUS_201.82
  base_path: ../..
  platform: ps2
  compiler: MWCCPS2
  asm_path: asm
  src_path: src
  build_path: build
  ld_script_path: build/SLUS_201.82.ld
  symbol_addrs_path: config/SLUS_201.82/symbol_addrs.txt
  undefined_funcs_auto_path: config/SLUS_201.82/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/SLUS_201.82/undefined_syms_auto.txt
  find_file_boundaries: false
  migrate_rodata_to_functions: false
  asm_function_macro: glabel
  asm_data_macro: dlabel
  asm_jtbl_label_macro: jlabel
  asm_inc_header: ".set noat      /* allow manual use of $at */\n.set noreorder /* don't insert nops after branches */\n\n"
  section_order: [".text", ".data", ".rodata", ".bss"]
  generated_c_preamble: "#include \"common.h\""
  generated_s_preamble: ""
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 0
  data_string_guesser_level: 0
  asm_emit_size_directive: false
  gp_value: 0x006A77F0
segments:
  - name: main
    type: code
    start: 0x00000380
    vram: 0x00100000
    bss_size: 0x00014100
    subalign: 16
    subsegments:
      - [0x00000380, asm, crt0]
      - [0x00000470, asm, mw_runtime]
      - [0x00002840, asm, sdk_libgraph]
      - [0x00003D30, asm, sdk_libdma]
      - [0x000044D0, asm, sdk_libkernel]
      - [0x0000D020, asm, sdk_libpad]
      - [0x0000E550, asm, sdk_libcdvd]
      - [0x00011340, asm, sdk_libmc]
      - [0x000129E0, asm, sdk_libm]
      - [0x00015C80, asm, sdk_libc]
      - [0x0001F960, asm, game_00]
      - [0x00031AC0, c, game_00/func_00131740]
      - [0x00031B20, asm, game_00_1]
      - [0x00045D90, c, game_00/func_00145A10]
      - [0x00045DC0, asm, game_00_2]
      - [0x00045E10, asm, game_memcard]
      - [0x000482E0, asm, game_01]
      - [0x000579D0, c, game_01/func_00157650]
      - [0x00057A04, asm, game_01_1]
      - [0x00065200, c, game_01/func_00164E80]
      - [0x00065258, asm, game_01_2]
      - [0x0007F280, data, data_vu]
      - [0x00096400, data, data_sdk]
      - [0x000975D0, data, data_game]
      - [0x00599B80, rodata, rodata_00]
      - [0x0059FB80, bss, main_bss]
  - [0x0059FB80]
